services:
  # Web Service
  - type: web
    name: fashnai-api
    env: docker
    repo: https://github.com/zishan-sudo/fashnai.git
    rootDir: .
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://magenta-klepon-578cf8.netlify.app
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: DB_HOST
      - key: DB_PORT
        value: 5432
      - key: DB_USER
      - key: DB_PASS
      - key: DB_DATABASE
